### ISSUE TITLE
There was a problem generating the heat map

### ISSUE THREAD

**Issue by EmberXH** [Spider-scnu/TSP#6]
Thanks to your good work and the code you provided, this problem occurred while generating heat maps using the test sets and models you provided
![QQ截图20221122152232](https://user-images.githubusercontent.com/100256003/203251321-680fbea7-31ad-4917-bcdb-76fced0b5e60.png)

**Comment by AlexAuthor7** [comment]
Hi, Did you solve the problem? I had the same problem generating the heat map.

**Comment by AlexAuthor7** [comment]
> Thanks to your good work and the code you provided, this problem occurred while generating heat maps using the test sets and models you provided ![QQ截图20221122152232](https://user-images.githubusercontent.com/100256003/203251321-680fbea7-31ad-4917-bcdb-76fced0b5e60.png)

Hi, Did you solve the problem? I had the same problem generating the heat map.

**Comment by Spider-scnu** [comment]
Hi, i have not reproduced this problem when runnning the related codes. Please check the hyper-parameter of KNN.

**Comment by sjihf12** [comment]
I meet the same error while generating heat maps using the test sets and models(200-500-1000-10000) you provided

**Comment by sjihf12** [comment]
> Hi, Did you solve the problem? I had the same problem generating the heat map.

Hi, Did you solve the problem? I had the same problem generating the heat map.

**Comment by Spider-scnu** [comment]
Hi, taking more care of the format of your instances.

**Comment by xyfffff** [comment]
I also encountered the same problem. By the way, the input I used also came from the test_concorde provided.

**Comment by xyfffff** [comment]
I just download the tsp20_test_concorde.txt, tsp50_test_concorde.txt and so on from the provided link. After that I move all `tspXX_test_concorde.txt` into `./data`, then I just run `test...ipynb`. Then bug comes....

**Comment by LejunZhou** [comment]
I encountered the same issue. Please check the test-20-50-100.ipynb file. I suggest focusing on the output of test_one_tsp, especially the dimension of edges_values. According to your code, it generates a 4-dimensional output, but in the block below, you're trying to assign it to a 3-dimensional variable. To be honest, this seems unrelated to the instances. @Spider-scnu Could you try to explain what it means for the four dimension, I will really appreciate it.

**Comment by github-shamada** [comment]
Thank you for publishing the program code.
I am trying to run this code to conduct new research based on your work.
However, I faced the same problem as the people here.
I performed comprehensive testing on the operating environment, but the problem was not resolved.
Below is a detailed test report.
I would appreciate any hints that might help me.


Training Command
----------------------------------------------------------------------


### Installation Procedures

~~~bash
conda create -n attgcn_train python
conda install tensorboardX numpy pandas scikit-learn matplotlib seaborn scipy fastprogress networkx
conda install pytorch cudatoolkit=11.1 python=3.8 -c pytorch-lts -c nvidia
conda install conda-forge::debugpy
~~~

or

~~~bash
conda create -n attgcn_train python
conda install tensorboardX numpy pandas scikit-learn matplotlib seaborn scipy fastprogress networkx
conda install pytorch==1.7.0 cudatoolkit=11.0 python=3.8 -c pytorch
conda install conda-forge::debugpy
~~~

### Execution Command

jupyter nbconvert --to python train-20.ipynb
python train-20.py

Actually, the program needs to be slightly modified.


### Execution Result

works well


Inference Command
----------------------------------------------------------------------


### Installation Procedures

cf. https://stackoverflow.com/questions/75853863/install-pytorch-version-1-0-0-using-pip-or-cuda-in-2023

[torch1.X.0 + cuda10.2 + python3.Y]
~~~bash
conda create -n xxxxxxxxx python=3.Y
pip install torch===1.X.0 -f https://download.pytorch.org/whl/torch_stable.html
pip install tensorboardX numpy pandas scikit-learn matplotlib seaborn scipy fastprogress networkx
pip install cython tqdm
~~~

[torch1.X.0 + cuda10.1 + python3.Y]
~~~bash
conda create -n xxxxxxxxx python=3.Y
pip3 install torch==1.X.0 -f https://download.pytorch.org/whl/cu101/torch_stable.html
pip install tensorboardX numpy pandas scikit-learn matplotlib seaborn scipy fastprogress networkx
pip install cython tqdm
~~~

[torch==1.X.0 + cuda10.2 + python3.Y]
~~~bash
conda create -n xxxxxxxxx python=3.Y
pip3 install torch==1.X.0 -f https://download.pytorch.org/whl/cu92/torch_stable.html
pip install tensorboardX numpy pandas scikit-learn matplotlib seaborn scipy fastprogress networkx
pip install cython tqdm
~~~

### Execution Command

~~~bash
jupyter nbconvert --to python test-20-50-100.ipynb
python test-20-50-100.py
~~~

### Execution Result

[torch1.0.1 + cuda10.2 + python3.7] Freezing up (*1)
[torch1.1.0 + cuda10.2 + python3.7] Freezing up (*1)
[torch1.2.0 + cuda10.2 + python3.7] Freezing up (*1)
[torch1.3.0 + cuda10.2 + python3.7] Freezing up (*1)
[torch1.4.0 + cuda10.2 + python3.7] Freezing up (*1)
[torch1.5.0 + cuda10.2 + python3.7] Freezing up (*1)
[torch1.6.0 + cuda10.2 + python3.5] unable to install (*4)
[torch1.6.0 + cuda10.2 + python3.6] L323 CUBLAS error (*2)
[torch1.6.0 + cuda10.1 + python3.6] L323 CUBLAS error (*2)
[torch1.6.0 + cuda9.2  + python3.6] L323 CUBLAS error (*2)
[torch1.6.0 + cuda10.2 + python3.7] L323 CUBLAS error (*2)
[torch1.6.0 + cuda10.1 + python3.7] L323 CUBLAS error (*2)
[torch1.6.0 + cuda9.2  + python3.7] L323 CUBLAS error (*2)
[torch1.6.0 + cuda10.2 + python3.8] L299 ValueError (*3)
[torch1.6.0 + cuda10.1 + python3.8] L299 ValueError (*3)
[torch1.6.0 + cuda9.2  + python3.8] L299 ValueError (*3)

*1) Freezing up
The following instruction almost freezes. In fact, it completes if you wait a long time.
~~~bash
net = nn.DataParallel(ResidualGatedGCNModel(config, dtypeFloat, dtypeLong))
~~~

*2) CUBLAS error
~~~bash
Traceback (most recent call last):
  File "test-20-50-100.py", line 323, in <module>
    y_preds, loss = net.forward(x_edges, x_edges_values, x_nodes, x_nodes_coord, y_edges, edge_cw)
  File "/home/shamada/miniconda3/envs/testenv-py37-160/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 153, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/shamada/miniconda3/envs/testenv-py37-160/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/u/work0/shamada/AttGCN/Att-GraphConvNet/models/gcn_model.py", line 65, in forward
    x = self.nodes_coord_embedding(x_nodes_coord)  # B x V x H
  File "/home/shamada/miniconda3/envs/testenv-py37-160/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/shamada/miniconda3/envs/testenv-py37-160/lib/python3.6/site-packages/torch/nn/modules/linear.py", line 91, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/shamada/miniconda3/envs/testenv-py37-160/lib/python3.6/site-packages/torch/nn/functional.py", line 1676, in linear
    output = input.matmul(weight.t())
RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`
~~~

*3) Value Error
~~~bash
Traceback (most recent call last):
  File "/u/work0/shamada/AttGCN/Att-GraphConvNet/test-20-50-100.py", line 299, in <module>
    edges_values[i*threshold:(i+1)*threshold, ...] = edges_value
ValueError: setting an array element with a sequence. The requested array would exceed the maximum number of dimension of 3.
~~~

*4) Unable to install
Adding the following does not solve the problem:
~~~bash
conda config --set solver classic
~~~

**Comment by github-shamada** [comment]
Let me add one thing.
In the following environment, I was able to successfully run python test-20-50-100.py to completion, although it took quite a long time because it nearly froze.

~~~bash
conda create -n attgcn_test python
conda install pytorch==1.4.0 cudatoolkit=10.1 python=3.8 -c pytorch
conda install tensorboardX numpy pandas scikit-learn matplotlib seaborn scipy fastprogress networkx
conda install cython tqdm
conda install conda-forge::debugpy=1.8.1
~~~
